Feat/post delete feature and fetched latest changes on main
bpocrafael/microblog-project pull request #50
Opened 2023-10-09 03:32 UTC by mikco-hipe

### OVERVIEW

Added destroy() function to PostController
Used SoftDeletes to mark posts with deleted timestamps
Added delete in UserPostPlicy
Added a delete button on show.blade.php
Added destroy on routes

### SNIPPETS
![Screenshot 2023-10-09 105548](https://github.com/bpocrafael/microblog-project/assets/144191092/d59b480f-8cf2-444e-8fc3-9acd76c733ca)
![Screenshot 2023-10-09 110404](https://github.com/bpocrafael/microblog-project/assets/144191092/1f304c66-3ec9-4173-8279-68c2481b81b0)
![image](https://github.com/bpocrafael/microblog-project/assets/144191092/317a28d8-7bad-405a-b7cb-9c4cee70c485)

2023-10-09 03:48 UTC, hipe01mark commented on laravel-app/resources/views/home.blade.php
> +        </div>
indention please!

2023-10-09 03:48 UTC, hipe01mark approved these changes
LGTM 🙇

2023-10-09 03:48 UTC, mikco-hipe commented on laravel-app/resources/views/home.blade.php
> +        </div>
Yes sir 🙇

2023-10-09 03:53 UTC, rafael-parayno approved these changes

2023-10-09 03:53 UTC, rafael-parayno commented on laravel-app/app/Http/Controllers/PostController.php
> +     * Delete a post
Remove comment already understandable

2023-10-09 03:53 UTC, rafael-parayno commented on laravel-app/app/Policies/UserPostPolicy.php
> +     * Determine whether the user can delete the post.
Remove

2023-10-09 03:53 UTC, mikco-hipe commented on laravel-app/app/Http/Controllers/PostController.php
> +     * Delete a post
Got it sir 🙇

2023-10-09 03:54 UTC, mikco-hipe commented on laravel-app/app/Policies/UserPostPolicy.php
> +     * Determine whether the user can delete the post.
Got it sir 🙇

2023-10-09 04:58 UTC, hipe01mark approved these changes
LGTM 🙇

2023-10-09 09:57 UTC, hipe-francis requested changes

2023-10-09 09:57 UTC, hipe-francis commented on laravel-app/resources/views/post/show.blade.php
> +                            <form id="delete-post-form" method="POST" action="{{ route('post.destroy', $post) }}">
Shouldn't the destroy param be an id/column value?

2023-10-10 01:14 UTC, hipe-francis approved these changes
LGTM 🚀

2023-10-10 01:15 UTC, merged